name: Build and Test Java App

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-test-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Krok 1: Dry run – uruchomienie aplikacji
      - name: Dry run - Run the app
        run: mvn exec:java -Dexec.mainClass="app.Application"

      # Krok 2: Testy jednostkowe
      - name: Run Unit Tests
        run: mvn test

      # Krok 3: Pakowanie do formatu .jar
      - name: Package the application
        run: mvn package

      # Krok 4: Udostępnienie pliku .jar jako artefakt (v3)
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: orderapp-jar
          path: target/*.jar

